application edited by outside....
application edit started..............................
vairav is the king of the world.......................
public void m1()
{
	System.out.println("razatchintu");
}
